apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
   run: db1
   name:  db1
spec:
  containers:
  - name: db1
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: dbconfig1
          key: MYSQL_ROOT_PASSWORD