apiVersion: apps/v1
kind: Deployment
metadata:
  name: demors1
spec:
  replicas: 2
  selector:
    matchLabels:
      dep: cse
      batch: sixth
  template:
    metadata:
      labels:
        dep: cse
        batch: sixth
    spec:
      containers:
        - name: doc1
          image: nginx
