apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
spec:
  volumes: 
    - name: cache-volume
      emptyDir:
        medium: Memory 
        sizeLimit: 1Gi

  containers:
  - image: nginx
    name: pod1
    resources: 
      limits: 
        memory: 256Mi
        

    volumeMounts: 
       - name: cache-volume
         mountPath: /cache
