apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multipod
  name: multipod
spec:
  volumes:
    - name: vol1
      emptyDir:
        sizeLimit: 1Gi

  containers:
  - args:
    - sleep
    - "10000"
    image: ubuntu
    name: pod1

    volumeMounts:
       - name: vol1
         mountPath: /shared

  - image: nginx
    name: pod2

    volumeMounts:
       - name: vol1
         mountPath: /data
