apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multipod
  name: multipod
spec:
  volumes: 
    - name: cache-volume
      emptyDir:
        medium: Memory 
        sizeLimit: 1Gi

  containers:
  - args:
    - sleep
    - "10000"
    image: ubuntu
    name: pod1
    resources: 
      limits: 
        memory: 256Mi

    volumeMounts: 
       - name: cache-volume
         mountPath: /shared

  - image: nginx
    name: pod2
    resources: 
      limits: 
        memory: 256Mi
        
    volumeMounts: 
       - name: cache-volume
         mountPath: /data
