apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
spec:
  containers:
  - env:
    - name: batch
      value: cka3
    - name: name
      value: reja
    image: nginx
    name: pod1