apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      volumes:
        - name: vol1
          hostPath:
            path: "/mnt/webhost"
            type: DirectoryOrCreate
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
          - name: vol1
            mountPath: "/usr/share/nginx/html"
            readOnly: true