apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default: # this section defines default limits
      cpu: 200m
    defaultRequest: # this section defines default requests
      cpu: 200m
    max: # max and min define the limit range
      cpu: "200m"
    min:
      cpu: 200m
    type: Container
