apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod2
  name: pod2
spec:
  containers:
  - image: nginx
    name: pod2
    resources:
     requests:
       cpu: 256m
       memory: 256Mi
     limits:
       cpu: 500m
       memory: 500Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
