apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: manual
  name: manual
spec:
  nodeName: worker1
  containers:
  - image: nginx
    name: manual
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
