apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nfsweb1
  name: nfsweb1
spec:
  volumes:
    - name: webvol1
      nfs:
       server: 172.16.0.8 
       path: /shared/nfsvol1
  containers:
  - image: nginx
    name: web1
    volumeMounts:
      - name: webvol1
        mountPath: "/usr/share/nginx/html"