apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      volumes:
        - name: vol1
          nfs:
           server: 172.16.0.8
           path: "/shared/nfsvol1"
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
          - name: vol1
            mountPath: "/usr/share/nginx/html"
#            readOnly: true