apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nodeselector
  name: nodeselector
spec:
  nodeSelector:
    disk: nvme
  containers:
  - image: nginx
    name: manual
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}