apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web
  name: web
spec:
  affinity:
   nodeAffinity:
     preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: size
            operator: In
            values:
            - large 
  containers:
  - image: nginx
    name: web 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}