apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web
  name: web
spec:
  affinity:
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
         - matchExpressions:
             - key: size
               operator: In 
               values:
                - small
  containers:
  - image: nginx
    name: web 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}