apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod2
  name: pod2
spec:
  requests: 
      cpu: 1
      memory: 2Gi
  containers:
  - image: nginx:alpine
    name: pod2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
