apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
spec:
  volumes:
    - name: dol1
      persistentVolumeClaim:
        claimName: pvc1
  containers:
    - name: pv-pod
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: dol1

