apiVersion: v1
kind: ReplicationController
metadata:
  name: demorc1
spec:
  replicas: 2
  template:
    metadata:
      name: pod1
      labels:
        app: web
    spec:
      containers:
        - name: doc1
          image: nginx
          
