apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ext1
  name: ext1
spec:
  externalName: abc.com
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ext1
  type: ExternalName
status:
  loadBalancer: {}
